USE MYSQL_TRAINING;

#Create database
# CREATE SCHEMA|DATABASE <DBNAME>;

CREATE SCHEMA mysql_training;

#Create table syntax
# CREATE TABLE <TABLENAME> (FIELDNAME WITH DATA TYPE);

#DataTypes
#Number -> TINYINT(4), SMALLINT, MEDIUMINT, INT(11), BIGINT, FLOAT(10,2), DOUBLE, DECIMAL
#String -> CHAR(10), VARCHAR(10), TEXT
#Date and Time -> DATE, TIME, TIMESTAMP
#BLOB, CLOB

CREATE TABLE EMPLOYEE (
    ID INT AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    AGE INT NOT NULL,
    GENDER CHAR(1),
    SALARY DOUBLE,
    DESIGNATION VARCHAR(50),
    DEPARTMENT VARCHAR(50),
    COUNTRY VARCHAR(30),
    PRIMARY KEY (ID)    
);

CREATE TABLE COUNTRY (
    ID INT AUTO_INCREMENT,
    CODE VARCHAR(3) NOT NULL,
    NAME VARCHAR(30) NOT NULL,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);


# ALTER STATEMENT EXAMPLES - REPLACE COUNTRY COLUMN WITH COUNTRY_ID
ALTER TABLE EMPLOYEE
	CHANGE COUNTRY COUNTRY_ID VARCHAR(30); 
 
ALTER TABLE EMPLOYEE
	DROP COLUMN COUNTRY_ID;
    
ALTER TABLE EMPLOYEE
	ADD COLUMN COUNTRY_ID INT NOT NULL;    
    
ALTER TABLE EMPLOYEE
	MODIFY COLUMN COUNTRY_ID INT;      
    
ALTER TABLE EMPLOYEE
	ADD FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY(ID) ON DELETE CASCADE;

ALTER TABLE EMPLOYEE
	DROP FOREIGN KEY constraint_name;	
    
# LIST CONSTRAINTS (Get constraint name from below query)
SELECT * FROM information_schema.table_constraints WHERE constraint_schema = 'mysql_training';
SELECT * FROM information_schema.referential_constraints WHERE constraint_schema = 'mysql_training';

# Table description details
DESCRIBE EMPLOYEE;    
DESCRIBE COUNTRY;